### ISSUE TITLE
Installation issue creating an alias to ldoc.lua

### ISSUE THREAD

**Issue by ernestbofill** [lunarmodules/ldoc#156]
I cannot complete installation. When I type the command to create the alias to ldoc.lua "lua /path/to/ldoc/ldoc.lua $*" I get the following result:
<code>no field package.preload['pl.class']
    no file '/opt/local/share/lua/5.2/pl/class.lua'
    no file '/opt/local/share/lua/5.2/pl/class/init.lua'
    no file '/opt/local/lib/lua/5.2/pl/class.lua'
    no file '/opt/local/lib/lua/5.2/pl/class/init.lua'
    no file './pl/class.lua'
    no file '/opt/local/lib/lua/5.2/pl/class.so'
    no file '/opt/local/lib/lua/5.2/loadall.so'
    no file './pl/class.so'
    no file '/opt/local/lib/lua/5.2/pl.so'
    no file '/opt/local/lib/lua/5.2/loadall.so'
    no file './pl.so'
stack traceback:
    [C]: in function 'require'
    /Users/ernestbofill/LDoc/ldoc.lua:19: in main chunk
    [C]: in ?</code>

May it be that I installed luarocks with mac ports?

Between, I want to use ldoc with Corona sdk projects. Will it work? Do I need any extra setting up for it?

Thanks for your support and for maintaining this tool
Ernest B.

**Comment by alerque** [comment]
It shouldn't matter how you installed `luarocks`. If you install LDoc *via* luarocks it will add an `ldoc` binary in the appropriate system or user local path. You shouldn't need to alias anything yourself since luarocks will figure out the relation to where it installed Penlight and where it installed LDoc.

If you still have an issue feel free to comment.
