### ISSUE TITLE
Bugs in the documentation

### ISSUE THREAD

**Issue by msva** [lunarmodules/ldoc#211]
Hi there!
It seems, there is a few bugs in the doc.md:
1) it links to `@list.moon`, while there is only `List.moon`.
That leads to

```
doc/doc.md:725: module not found: list list.moon
```

2) doc/config.ld contains `format=discount`, which leads to

```
format: discount not found, using markdown
```

**Comment by stevedonovan** [comment]
Thanks, I just noticed this issue.  Comes from doing too much testing on case-insensitive file systems ;)

As for second issue, it's deliberate. LDoc falls back to the default markdown processor if it can't find discount, which I like because it's really fast.  Easy to install with luarocks, although not everyone uses LR.  The main thing is that the result _should_ be pretty close, either way.

**Comment by mpeterv** [comment]
@stevedonovan By the way, the latest markdown on the LuaRocks is now Lua 5.2/5.3 compatible, so you can drop bundled ldoc.markdown if you want.

**Comment by stevedonovan** [comment]
A good point - I should certainly synchronize with latest Markdown (I suspect that a number of us made markdown.lua work with modern Lua separately).  But (again) not everyone uses LuaRocks so I didn't want to add too many external dependencies.

**Comment by msva** [comment]
Not everyone uses luarocks, but many using system-wide package manager, which, most of time, able to install lua packages system-wide ;)

**Comment by stevedonovan** [comment]
Yes - Debian has both markdown.lua and lua-discount, although of course the LDoc package is going to be a little bit behind.  I understand the principle of not keeping own copies, but it is a small file which makes life easier for people.  I'm prepared to keep it in sync with the latest.

**Comment by alerque** [comment]
It seems the original report has been fixed.
