### ISSUE TITLE
Part after dot is ignored

### ISSUE THREAD

**Issue by madprops** [lunarmodules/LDoc#374]
```
/**
 * Define it the client must be iconify, i.e. only visible in
 *   taskbar.
 *
 * Minimized clients are still part of tags and screens, but
 * they are not displayed. You can unminimize using `c.minimized = false`,
 * but if you also want to set the focus, it is better to use:
 *
 *    c:activate { context = "unminimized", raise = true }
 *
 * @DOC_sequences_client_minimize1_EXAMPLE@
 *
 * @property minimized
 * @tparam boolean minimized
 * @propemits false false
 * @see hidden
 * @see isvisible
 * @see activate
 */
```

That results in:

![docbug](https://user-images.githubusercontent.com/206498/173893907-6cdc3173-1eff-49e1-a8a5-ea379e2da9bc.jpg)

Is this a bug?

**Comment by alerque** [comment]
No, this is not a bug. You'll find it [in the documentation here](https://stevedonovan.github.io/ldoc/manual/doc.md.html)

> All doc comments start with a summary sentence, that ends with a period or a question mark. An optional description may follow. Normally the summary sentence will appear in the module contents.

You can fudge this by not following the period with a space. Note how it didn't stop at the first dot in your `i.e.`? You could use a non-breaking space instead of a space or insert some other punctuation immediately after the dot.

Personally I'd just use clearer help text that doesn't need an `i.e.` to explain it, perhaps:

```
/**
 * Set minimized property on client window so it only shows in the taskbar.
 *
 * ...
```

**Comment by Aire-One** [comment]
Thank you for the clarification @alerque :)
