### ISSUE TITLE
LuaRocks module: broken link to project homepage

### ISSUE THREAD

**Issue by deining** [lunarmodules/LDoc#380]
Module `ldoc` is available on this [page](https://luarocks.org/modules/luarocks/ldoc) on `luarocks.org`. This page shows a broken link to the project home page:
http://stevedonovan.github.com/ldoc

Were great if this link could be corrected to:
https://github.com/lunarmodules/LDoc

**Comment by alerque** [comment]
As of yet we have not republished the docs under this org. We do need to do that, but the old docs link in still correct until we cut a new release.

That being said the link was broken because it wasn't even the right link to the *old* docs location. It should be `.io` not `.com`. I've corrected that.

Thanks for the report.

**Comment by deining** [comment]
> As of yet we have not republished the docs under this org. We do need to do that, but the old docs link in still correct until we cut a new release.
> 
> That being said the link was broken because it wasn't even the right link to the _old_ docs location. It should be `.io` not `.com`. I've corrected that.

Thanks, glad we got that resolved so fast! The link to the docs is correct now. Inside the docs, the link to the .zip archive is broken (should be `.io` not `.com`). This will be fixed once #379 was accepted and merged and a new release will be published. 

> Thanks for the report.

You are welcome.
