### ISSUE TITLE
[Meta] Is this repo dead?

### ISSUE THREAD

**Issue by lionkor** [lunarmodules/LDoc#391]
Sorry if this is rude, but we were considering using LDoc internally in one of the projects I lead, but I run into the issue #258, and I'd fix it, but there seem to be 24 PRs and none of them were looked at since some time 2022.

LuaDoc is even more abandoned, so I'm simply curious if this is active.

**Comment by Tieske** [comment]
It's not dead. It replaced LuaDoc (so that one can be considered dead), but it is looking for maintainers. See https://github.com/lunarmodules for our role in it. I use it for all my projects. There are some bugs, but usually I manage to work around it. 

fwiw; the bugs are pretty stable 😄 , so once I have stuff up, it just keeps working.

**Comment by alerque** [comment]
Down to 15 PRs.

If you want to help get it down farther feel free to jump in with PR reviews. Extra eyes with comments to say you checked things out and they work or X needs fixing is the best way to move things along and cut down on the time maintainers need to invest out of pocket.
