### ISSUE TITLE
--all option is broken

### ISSUE THREAD

**Issue by Tieske** [lunarmodules/ldoc#61]
locals are always enabled, even if not specified (i'm using the `config.ld` configuration file)

**Comment by alerque** [comment]
I recreated the MWE here as best I could using v1.5.0 and generating docs with and without `--all` definitely produced a difference.

Baring further information I'm going to assume this is fixed, but it is also possible my MWE wasn't the same since this issue doesn't have the full MWE with a config file and all parts necessary to generate output. If something still doesn't work feel free to comment with the remaining parts of an MWE and re-open!
